name: Trigger GitLab CI

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab Pipeline
        run: |
          curl --request POST \
               --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
               --form "ref=main" \
               "https://gitlab.com/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline"
